api = "0.2"

[buildpack]
  id = "io.avarteqgmbh.buildpacks.git-ssh"
  name = "GIT SSH buildpack"
  homepage = "https://github.com/avarteqgmbh/git-ssh-buildpack"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
