api = "0.2"

[buildpack]
id = "io.avarteqgmbh.buildpacks.git-ssh"
version = "0.5.1"
name = "GIT SSH buildpack"

[metadata]
include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
